# Practice 2 - Numpy
Students are required to complete the code implementation for Problems 1-7, and to conduct exploratory analysis for Problems 8 and 9, providing well-reasoned answers to the corresponding questions.

                                                                                                      
### DDL: Oct.12
* The practice will be checked in this lab class or the next lab class before the DDL by teachers or SAs.

#### What will be tested: 
* That you understand every line of your code, not just copy from somewhere 
* That your program compiles correctly
* Correctness of the program logic 
* That the result is obtained in a reasonable time 

#### Grading: 
* Submissions on time: 60-100 points.
* Late submissions  : 0 points. 

**Q1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.**

In [15]:
#1
import numpy as np
a = np.zeros((10, 10))
a[0, :] = 1
a[-1, :] = 1
a[:, 0] = 1
a[:, -1] = 1
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Q2. Create a 5*5 matrix with each row being 0 to 4.**

In [16]:
#2
import numpy as np
a = np.arange(5)
matrix = np.tile(a, (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**Q3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]]).**

In [17]:
#3
import numpy as np
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Q4. output all the odd numbers in the array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].**
     
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [18]:
#4
import numpy as np
a = np.arange(10)
b = []
for i in range(len(a)):
    if a[i] % 2 == 1:
        b.append(a[i])
print(b)

[1, 3, 5, 7, 9]


**Q5. Apply Z-score normalization to a 5×5 random matrix.**

In [19]:
#5
import numpy as np
a = np.random.random((5, 5))
norm = np.linalg.norm(a)
a = a / norm
print(a)

[[0.28942623 0.26425135 0.21447179 0.01917395 0.05515076]
 [0.25864487 0.07324792 0.24247093 0.18287856 0.23367633]
 [0.08356375 0.0986171  0.26694096 0.18622189 0.18470832]
 [0.26102228 0.07265229 0.26272375 0.05004382 0.21426267]
 [0.21615692 0.10597188 0.28458083 0.2809607  0.11137511]]


**Q6.Generate a random 10×2 matrix representing Cartesian coordinates, and transform the coordinates into their polar form.**

In [20]:
#6
import numpy as np
a = np.random.random((10, 2))
r = np.sqrt(np.sum(a**2, axis=1))
t = np.arctan2(a[:, 1], a[:, 0])
print(f'x, y : {a[:, 0]}, {a[:, 1]}')
print(f'r, theta : {r}, {t}')

x, y : [0.21815273 0.87804813 0.21005378 0.07323662 0.94394132 0.87169916
 0.82061182 0.53288648 0.15787568 0.16620467], [0.79376085 0.45254503 0.70850689 0.56590324 0.10031426 0.87610987
 0.47699221 0.7351998  0.56133507 0.02441248]
r, theta : [0.82319311 0.98780844 0.73898891 0.57062254 0.94925664 1.23589156
 0.94917086 0.90801253 0.58311388 0.16798798], [1.30258415 0.47589069 1.28257764 1.44209621 0.10587433 0.78792172
 0.52652919 0.94360706 1.29662855 0.14583919]


**Q7.Given the vector [1, 2, 3, 4, 5], construct a new vector by inserting three consecutive zeros between each element.**

In [21]:
#7
import numpy as np
a = np.arange(1, 6)
b = np.zeros(4*len(a))
b[::4] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


**Q8. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))


In [22]:
#8
'''
nan, nan plus any number is still nan
false, nan is not equal to anything, including itself
true, nan is unordered, so comparisons are always false
nan, any arithmetic operation with nan results in nan
false, nan is not equal to anything, including itself
false, 0.1 cannot be precisely represented in binary floating point
'''

import numpy as np
print(0*np.inf)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


**Q9. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**
(Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)




In [23]:
#9
'''
divided by 0 is not defined, so not a number
with floor division, maybe become 0?
a number that reaches the limit of the floating point precision
'''
import numpy as np
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\wendy\AppData\Local\Temp\ipykernel_19152\2664377034.py:8: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
C:\Users\wendy\AppData\Local\Temp\ipykernel_19152\2664377034.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))
C:\Users\wendy\AppData\Local\Temp\ipykernel_19152\2664377034.py:10: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))
